In [ ]:
from sentence_transformers import SentenceTransformer
from huggingface_hub import login

login(token="hf_cBjj")

s_model = SentenceTransformer("magibu/embeddingmagibu-152m")
s_sentences = [
    "Bu mutlu bir adamdır",
    "Bu mutlu bir kadın",
    "Akşam sinemaya gideceğim",
    "Bugün hava güneşli"
]
s_embeddings = s_model.encode(s_sentences)

s_similarities = s_model.similarity(s_embeddings, s_embeddings)

f_model = SentenceTransformer("final_model")
f_embeddings = f_model.encode(s_sentences)
f_similarities = f_model.similarity(f_embeddings, f_embeddings)

model = SentenceTransformer("google/embeddinggemma-300m")

embeddings = model.encode(s_sentences)

similarities = model.similarity(embeddings, embeddings)

print("distilled similarities")
print(s_similarities)
print("google similarities")
print(similarities)
print("final model similarities")
print(f_similarities)

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.


distilled similarities
tensor([[1.0000, 0.7753, 0.3576, 0.3900],
        [0.7753, 1.0000, 0.3473, 0.3986],
        [0.3576, 0.3473, 1.0000, 0.4589],
        [0.3900, 0.3986, 0.4589, 1.0000]])
google similarities
tensor([[1.0000, 0.6366, 0.2575, 0.2891],
        [0.6366, 1.0000, 0.2577, 0.3204],
        [0.2575, 0.2577, 1.0000, 0.3144],
        [0.2891, 0.3204, 0.3144, 1.0000]])
final model similarities
tensor([[1.0000, 0.9989, 0.3617, 0.1673],
        [0.9989, 1.0000, 0.3572, 0.1654],
        [0.3617, 0.3572, 1.0000, 0.3862],
        [0.1673, 0.1654, 0.3862, 1.0000]])


In [ ]:
from sentence_transformers import SentenceTransformer
from huggingface_hub import login

login(token="hf_cBjj")

s_model = SentenceTransformer("alibayram/distilled-sentence-transformer-c400")
s_model

/Users/alibayram/.pyenv/versions/3.13.3/lib/python3.13/site-packages/keras/src/export/tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):
Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.


SentenceTransformer(
  (0): Transformer({'max_seq_length': 2048, 'do_lower_case': False, 'architecture': 'Gemma3TextModel'})
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
  (2): Dense({'in_features': 768, 'out_features': 3072, 'bias': False, 'activation_function': 'torch.nn.modules.linear.Identity'})
  (3): Dense({'in_features': 3072, 'out_features': 768, 'bias': False, 'activation_function': 'torch.nn.modules.linear.Identity'})
  (4): Normalize()
)

In [3]:
s_model.push_to_hub("magibu/embeddingmagibu-152m", exist_ok=True)

Processing Files (0 / 0): |          |  0.00B /  0.00B            

New Data Upload: |          |  0.00B /  0.00B            

'https://huggingface.co/magibu/embeddingmagibu-152m/commit/12886ac714587372def3434a8ae5b7edd08eece1'

In [6]:
import mteb
from mteb import MTEB
from sentence_transformers import SentenceTransformer

# Get the Turkish benchmark
mteb_tr = mteb.get_benchmark("MTEB(Turkish)")

In [7]:
# Initialize your model
model = SentenceTransformer(
    "alibayram/embeddingmagibu-200m",
    trust_remote_code=True,
)

# Initialize MTEB evaluation
evaluation = MTEB(tasks=mteb_tr)

modules.json:   0%|          | 0.00/573 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/988 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/404M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/740 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/13.7M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/312 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/134 [00:00<?, ?B/s]

2_Dense/model.safetensors:   0%|          | 0.00/4.72M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/134 [00:00<?, ?B/s]

3_Dense/model.safetensors:   0%|          | 0.00/4.72M [00:00<?, ?B/s]

In [9]:
# Run evaluation
results = evaluation.run(model)

───────────────────────────────────────────────── Selected tasks  ─────────────────────────────────────────────────

Retrieval

- CQADupstackGamingRetrievalTR, s2p

- FiQA2018TR, s2p

- QuoraRetrievalTR, s2s

- SCIDOCSTR, s2p

- SciFactTR, s2p

Batches:   0%|          | 0/47 [00:00<?, ?it/s]

Batches:   0%|          | 0/64 [00:00<?, ?it/s]

ERROR:mteb.evaluation.MTEB:Error while evaluating CQADupstackGamingRetrievalTR: MPSGaph does not support tensor dims larger than INT_MAX


RuntimeError: MPSGaph does not support tensor dims larger than INT_MAX